inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'api_generator/**/*'

Gemspec/RequireMFA:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

Metrics:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Naming/FileName:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/LineLength:
  Enabled: false
