inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

RSpec/ImplicitExpect:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

Metrics:
  Enabled: false
