require: rubocop-rake
AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'Rakefile'
  NewCops: enable

Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false