name: Publish Docs to Github Pages
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  update-docs:
    runs-on: ubuntu-latest
    name: Update gh-pages with docs
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Install Ruby gems
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev
          rake bundle:clean
          rake bundle:install
      - name: Generate Docs
        run: rake gh_pages
      - name: Commit Docs Change
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: 'docs/* -f'
      - name: Deploy Docs to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: true
          enable_jekyll: true
