name: Integration with Unreleased OpenSearch

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        opensearch_ref: [ '1.x', '2.x', '2.0', 'main' ]
        ruby_version: 3.1
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}

      - name: Checkout OpenSearch
        uses: actions/checkout@v3
        with:
          repository: opensearch-project/OpenSearch
          ref: ${{ matrix.opensearch_ref }}
          path: opensearch

      - name: Get OpenSearch branch top
        id: get-key
        working-directory: opensearch
        run: echo key=`git log -1 --format='%H'` >> $GITHUB_OUTPUT

      - name: Restore cached build
        id: cache-restore
        uses: actions/cache/restore@v3
        with:
          path: opensearch/distribution/archives/linux-tar/build/distributions
          key: ${{ steps.get-key.outputs.key }}

      - name: Assemble OpenSearch
        if: steps.cache-restore.outputs.cache-hit != 'true'
        working-directory: opensearch
        run: ./gradlew :distribution:archives:linux-tar:assemble

      - name: Save cached build
        if: steps.cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: opensearch/distribution/archives/linux-tar/build/distributions
          key: ${{ steps.get-key.outputs.key }}

      - name: Run OpenSearch
        working-directory: opensearch/distribution/archives/linux-tar/build/distributions
        run: |
          tar xf opensearch-min-*
          ./opensearch-*/bin/opensearch &
          for attempt in {1..20}; do sleep 5; if curl -s localhost:9200; then echo '=====> ready'; break; fi; echo '=====> waiting...'; done

      - name: Checkout Ruby Client
        uses: actions/checkout@v2

      - name: Build and test with Rake
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev
          ruby -v
          rake bundle:clean
          rake bundle:install

      - name: opensearch-ruby
        run: cd opensearch-ruby && bundle exec rake test:all
      - name: opensearch-transport
        run: cd opensearch-transport && bundle exec rake test:all
      - name: opensearch-api
        run: cd opensearch-api && bundle exec rake test:spec
      - name: opensearch-dsl
        run: cd opensearch-dsl && bundle exec rake test:all
      - name: opensearch-aws-sigv4
        run: cd opensearch-aws-sigv4 && bundle exec rake test:all

      - name: Save server logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: opensearch-logs-${{ matrix.opensearch_ref }}-ruby-${{ matrix.ruby_version }}
          path: opensearch/distribution/archives/linux-tar/build/distributions/**/logs/*
